default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  username: api
  password: zZ8xYz7KTLvvax
  database: api_production